apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tablet
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: tablet
  replicas: {{ .Values.tabletReplicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: tablet
  template:
    metadata:
      labels:
        app: tablet
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tablet
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |-
              echo "${HOSTNAME}" >> {{ printf "%s/name.txt" .Values.dataMountPath | quote }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: busybox:1.28
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: name-init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data-dir
              readOnly: false
      containers:
        - image: {{ .Values.image.openmldbImage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: tablet
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.containerPorts.tabletPort }}
          resources: {}
          env:
          - name: COMPONENT
            value: "tablet"
          - name: LD_LIBRARY_PATH
            value: {{ .Values.udfLibraryDir | quote }}
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data-dir
              readOnly: false
            - mountPath: {{ .Values.logMountPath }}
              name: log-dir
              readOnly: false
            - mountPath: /openmldb/conf/tablet.flags
              name: tablet-conf
              subPath: tablet.flags
      volumes:
      {{- if not .Values.persistence.enabled }}
      - name: data-dir
        emptyDir: {}
      {{- end}}
      {{- if not .Values.persistence.logDir.enabled }}
      - name: log-dir
        emptyDir: {}
      {{- end}}
      - name: tablet-conf
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: tablet.flags
            path: tablet.flags
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nameserver
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: nameserver
  replicas: {{ .Values.nameserverReplicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nameserver
  template:
    metadata:
      labels:
        app: nameserver
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nameserver
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |-
              echo "${HOSTNAME}" >> {{ printf "%s/name.txt" .Values.dataMountPath | quote }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: busybox:1.28
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: name-init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data-dir
              readOnly: false
      containers:
        - image: {{ .Values.image.openmldbImage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: nameserver
          ports:
            - containerPort: {{ .Values.containerPorts.nameserverPort }}
          resources: {}
          env:
          - name: COMPONENT
            value: "nameserver"
          volumeMounts:
            - mountPath: {{ .Values.dataMountPath }}
              name: data-dir
              readOnly: false
            - mountPath: {{ .Values.logMountPath }}
              name: log-dir
              readOnly: false
            - mountPath: /openmldb/conf/nameserver.flags
              name: nameserver-conf
              subPath: nameserver.flags
      volumes:
      {{- if not .Values.persistence.dataDir.enabled }}
      - name: data-dir
        emptyDir: {}
      {{- end}}
      {{- if not .Values.persistence.logDir.enabled }}
      - name: log-dir
        emptyDir: {}
      {{- end}}
      - name: nameserver-conf
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
          - key: nameserver.flags
            path: nameserver.flags

  {{- if or .Values.persistence.dataDir.enabled .Values.persistence.logDir.enabled }}
  volumeClaimTemplates:
    {{- if .Values.persistence.dataDir.enabled }}
    - metadata:
        name: data-dir
        {{- if .Values.persistence.annotations }}
        annotations: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.labels }}
        labels: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.labels "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.dataDir.size | quote }}
        {{- if .Values.persistence.dataDir.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.dataDir.selector "context" $) | nindent 10 }}
        {{- end }}
    {{- end}}
    {{- if .Values.persistence.logDir.enabled }}
    - metadata:
        name: log-dir
        {{- if .Values.persistence.annotations }}
        annotations: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.labels }}
        labels: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.labels "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.logDir.size | quote }}
        {{- if .Values.persistence.logDir.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.logDir.selector "context" $) | nindent 10 }}
        {{- end }}
    {{- end}}
  {{- end }}
