apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tablet
  namespace: openmldb
spec:
  serviceName: tablet
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: tablet
  template:
    metadata:
      labels:
        app: tablet
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tablet
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |-
              echo "${HOSTNAME}" >> "/openmldb/data/name.txt"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          name: name-init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /openmldb/data
              name: data-dir
              readOnly: false
      containers:
        - image: openmldb-online:0.8.1
          name: tablet
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 10921
          resources: {}
          env:
          - name: COMPONENT
            value: "tablet"
          - name: LD_LIBRARY_PATH
            value: "/openmldb/udf"
          volumeMounts:
            - mountPath: /openmldb/data
              name: data-dir
              readOnly: false
            - mountPath: /openmldb/conf/tablet.flags
              name: tablet-conf
              subPath: tablet.flags
      volumes:
      - name: data-dir
        emptyDir: {}
      - name: tablet-conf
        configMap:
          name: tablet-config
          items:
          - key: tablet.flags
            path: tablet.flags
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nameserver
  namespace: openmldb
spec:
  serviceName: nameserver
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nameserver
  template:
    metadata:
      labels:
        app: nameserver
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nameserver
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |-
              echo "${HOSTNAME}" >> "/openmldb/data/name.txt"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          name: name-init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /openmldb/data
              name: data-dir
              readOnly: false
      containers:
        - image: openmldb-online:0.8.1
          name: nameserver
          ports:
            - containerPort: 7527
          resources: {}
          env:
          - name: COMPONENT
            value: "nameserver"
          volumeMounts:
            - mountPath: /openmldb/data
              name: data-dir
              readOnly: false
            - mountPath: /openmldb/conf/nameserver.flags
              name: nameserver-conf
              subPath: nameserver.flags
      volumes:
      - name: data-dir
        emptyDir: {}
      - name: nameserver-conf
        configMap:
          name: nameserver-config
          items:
          - key: nameserver.flags
            path: nameserver.flags
